using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace MQL4CSharp.Base.Enums
{
    public enum SYMBOL_INFO_DOUBLE
    {
        SYMBOL_BID = 1,
        SYMBOL_BIDHIGH,
        SYMBOL_BIDLOW,
        SYMBOL_ASK,
        SYMBOL_ASKHIGH,
        SYMBOL_ASKLOW,
        SYMBOL_LAST,
        SYMBOL_LASTHIGH,
        SYMBOL_LASTLOW,
        SYMBOL_POINT,
        SYMBOL_TRADE_TICK_VALUE,
        SYMBOL_TRADE_TICK_VALUE_PROFIT,
        SYMBOL_TRADE_TICK_VALUE_LOSS,
        SYMBOL_TRADE_TICK_SIZE,
        SYMBOL_TRADE_CONTRACT_SIZE,
        SYMBOL_VOLUME_MIN,
        SYMBOL_VOLUME_MAX,
        SYMBOL_VOLUME_STEP,
        SYMBOL_VOLUME_LIMIT,
        SYMBOL_SWAP_LONG,
        SYMBOL_SWAP_SHORT,
        SYMBOL_MARGIN_INITIAL,
        SYMBOL_MARGIN_MAINTENANCE,
        SYMBOL_MARGIN_LONG,
        SYMBOL_MARGIN_SHORT,
        SYMBOL_MARGIN_LIMIT,
        SYMBOL_MARGIN_STOP,
        SYMBOL_MARGIN_STOPLIMIT,
        SYMBOL_SESSION_VOLUME,
        SYMBOL_SESSION_TURNOVER,
        SYMBOL_SESSION_INTEREST,
        SYMBOL_SESSION_BUY_ORDERS_VOLUME,
        SYMBOL_SESSION_SELL_ORDERS_VOLUME,
        SYMBOL_SESSION_OPEN,
        SYMBOL_SESSION_CLOSE,
        SYMBOL_SESSION_AW,
        SYMBOL_SESSION_PRICE_SETTLEMENT,
        SYMBOL_SESSION_PRICE_LIMIT_MIN,
        SYMBOL_SESSION_PRICE_LIMIT_MAX



    }
}
